apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  labels:
    app: {{ .Values.backend.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
    nodePort: {{ .Values.backend.nodePort }}
