apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
